apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: ai-devops-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/yu900701/ai-devops-platform-gitops.git

    targetRevision: main

    path: apps

  destination:
    server: https://kubernetes.default.svc

    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true