apiVersion: apps/v1
kind: Deployment

metadata:
  name: ai-devops-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ai-devops-app

  template:
    metadata:
      labels:
        app: ai-devops-app

    spec:
      containers:
        - name: ai-devops-container

          image: ghcr.io/yu900701/ai-devops-app:dd0d9b2

          imagePullPolicy: Always

          ports:
            - containerPort: 8000